import './globals.css'
import { pageStore } from './zustand/zustand'

import Header from './component/header'
import { fetchContentful } from './contentful/contentful'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const data = await fetchContentful('pageOnoff');
  const exhibitionOn =  data[0].fields.exhibitionOnOff;
  const archiveOn = data[0].fields.archiveOnOff
  
  return (
    <html>
      <body>
        <div>
          <Header exhibitionOn={exhibitionOn} archiveOnOn={archiveOn} />
          {children}
        </div> 
      </body>
    </html>
  )
}
