import './globals.css'

import Header from './component/header'
import Footer from './component/footer'

export const metadata = {
  title: 'Graduation Exhibition',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  /*
  * 2025.12
  * pageOnOff는 사용이 안되고있음.
  * 필요없는 api 호출이므로 제거
  * Header에 파ㅁ라미터로 넘기던 것도 제거*/
  // const data = await fetchContentful('pageOnoff');
  // const exhibitionOn =  data[0].fields.exhibitionOnOff;
  // const archiveOn = data[0].fields.archiveOnOff;

  return (
    <html>
      <body>
        <div className="wrap"> {/* ✅ class → className 으로 변경 */}
          <Header/>
          {children}
          <Footer />
        </div> 
      </body>
    </html>
  )
}
